### ISSUE TITLE
Deleting entities here will sometimes create invalid entities in loop 

### ISSUE THREAD

**Issue by ErikBehar** [gale93/randballs#2]
https://github.com/gale93/randballs/blob/3e93ab93968351b1eb4da253e094dd60922728d3/systems/collisionsystem.cpp#L103

Suggest you put entities to delete in a vector and delete them at end of loop. Or always check the first entity and break in the second loop like: 

```if (!registry->valid(*it)) break; ```

**Comment by gale93** [comment]
Hi ! I didn't think anyone would ever look at this code :D
Yes that's a mistake and need to be fixed.
If you want to make a PR you are welcome, otherwise I'll rebuild the game on weekend :)

**Comment by ErikBehar** [comment]
you are listed as an example in the EnTT readme and I felt it was a good simple example to look at to learn how it works. It was sort of a let down to see it crash almost immediately after getting it to build, so I wanted to correct the issues as a learning experience. I would have put in PR's instead of issues, but to get it to build I ended up making a lot of changing  "\\" to "/"  all over the place.

**Comment by gale93** [comment]
Oh, that's a shame, I'll fix that too asap ;)
